### PR TITLE
Support alternate clients

### PR DESCRIPTION
**Pull request by zielu**
Hi,
this is a huge PR that:
- introduces possibility to have different MQTT client backends.
- adds hivemq-mqtt-client - motivation was to have websockets support
- fixes small issue in clientId generation
- improves logging all over the place

It's actually hard to split it into smaller ones.

### CODE REVIEW

**Comment by jinfahua** [comment]
@zielu It's so cool,  really appreciate. We'll review your code, test code compliance and also check if it has any problems when with large scale performance testing. We'll keep you update if having any problems.

**Comment by chongyuanyin** [comment]
@zielu your commits especially the websocket support do really great helps, thanks! 

We are doing more tests on the code and are also considering removing the fuse client from UI as the hivemq client supports more protocols.

Also, would like to check with you about the hivemq dependency in pom.xml, which is the development version, should we wait for the next stable release?

**Comment by zielu** [comment]
@chongyuanyin I kept fuse because it supports SNI. Hive fixes that in next stable (1.1.3) which seems to be almost ready to release. I would hold off with fuse removal till hivemq 1.1.3 not to loose functionality.

**Comment by zielu** [comment]
@chongyuanyin I updated hivemq-client version to new release with SNI support

**Pull request merged**
